# Basic Site Settings
locale            : "en-US"
site_theme        : "default"
title             : "Nodira Bekmatova | Academic Portfolio"
title_separator   : "-"
name              : "Nodira Bekmatova"
description       : "PhD Candidate in Linguistics & Senior English Educator"
url               : "https://nodira-bekmatova.github.io"
baseurl           : ""
repository        : "nodira-bekmatova/nodira-bekmatova.github.io"

# Site Author
author:
  # Biographic information
  avatar          : "/images/nodira-profile.jpg"
  name            : "Nodira Bekmatova"
  pronouns        : "she/her"
  bio             : "PhD Candidate in Linguistics | Senior English Educator"
  location        : "Uzbekistan"
  employer        : "Specialized School"
  uri             : # URL
  email           : "nodirabek.84@gmail.com"

  # Academic websites
  academia        : # URL
  arxiv           : # URL
  googlescholar   : # URL
  orcid           : # URL
  semantic        : # URL
  ssrn            : # URL
  pubmed          : # URL
  researchgate    : # URL
  scopus          : # URL
  zotero          : # URL

  # Social media
  linkedin        : # Username
  twitter         : # Username
